export enum ImportErrorCode {
    // Validation — field / format / structure / state / file-level
    FIELD_BLANK = "FIELD_BLANK",
    FIELD_INVALID = "FIELD_INVALID",
    MISSING_COLUMN = "MISSING_COLUMN",
    ROW_SHAPE = "ROW_SHAPE",
    CLASHING_INVALID = "CLASHING_INVALID",
    ELEMENT_STATUS_MISMATCH = "ELEMENT_STATUS_MISMATCH",
    NO_DATA_ROWS = "NO_DATA_ROWS",
    SPREADSHEET_CORRUPTION = "SPREADSHEET_CORRUPTION",
    FILE_UNREADABLE = "FILE_UNREADABLE",

    // Floor
    FLOOR_NOT_IN_PROJECT = "FLOOR_NOT_IN_PROJECT",
    FLOOR_MISMATCH = "FLOOR_MISMATCH",

    // Object
    OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND",
    OBJECT_DUPLICATE = "OBJECT_DUPLICATE",
    NAVISWORKS_MISMATCH = "NAVISWORKS_MISMATCH"
}
