enum PageNames {
  INTEGRATION_TEST_LOGIN = "INTEGRATION_TEST_LOGIN",
  ACCEPT_INVITATION = "ACCEPT_INVITATION",
  ORGANIZATION = "ORGANIZATION",
  ORGANIZATION_LIST = "ORGANIZATION_LIST",
  LOGIN = "LOGIN",
  NOT_FOUND = "NOT_FOUND",
  PROCORE_AUTHENTICATED = "PROCORE_AUTHENTICATED",
  PROGRESS_REPORT = "PROGRESS_REPORT",
  PROJECT = "PROJECT",
  PROJECT_REPORTS = "PROJECT_REPORTS",
  PROJECT_UPLOADS = "PROJECT_UPLOADS",
  PROJECT_VIEWER = "PROJECT_VIEWER",
  QUALITY_CONTROL_REPORT = "QUALITY_CONTROL_REPORT",
  PHOTOS = "PHOTOS"
}

export const ACCEPT_INVITATION = PageNames.ACCEPT_INVITATION;
export const ORGANIZATION = PageNames.ORGANIZATION;
export const ORGANIZATION_LIST = PageNames.ORGANIZATION_LIST;
export const LOGIN = PageNames.LOGIN;
export const NOT_FOUND = PageNames.NOT_FOUND;
export const PROCORE_AUTHENTICATED = PageNames.PROCORE_AUTHENTICATED;
export const PROGRESS_REPORT = PageNames.PROGRESS_REPORT;
export const PROJECT = PageNames.PROJECT;
export const PROJECT_REPORTS = PageNames.PROJECT_REPORTS;
export const PROJECT_UPLOADS = PageNames.PROJECT_UPLOADS;
export const PROJECT_VIEWER = PageNames.PROJECT_VIEWER;
export const QUALITY_CONTROL_REPORT = PageNames.QUALITY_CONTROL_REPORT;
export const PHOTOS = PageNames.PHOTOS;

export default PageNames;
