export enum PhotoRotationType {
    CAMERA_WORLD_MATRIX = "CAMERA_WORLD_MATRIX",
    RELATIVE_MINIMAP_BEARING = "RELATIVE_MINIMAP_BEARING",
    ABSOLUTE_MINIMAP_BEARING = "ABSOLUTE_MINIMAP_BEARING"
}

export default PhotoRotationType;
