export enum UserPermissionAction {
  ANY = "ANY",

  CREATE = "CREATE",

  GRANT_ROLE_SUPERADMIN = "GRANT_ROLE_SUPERADMIN",
  GRANT_ROLE_BASIC_USER = "GRANT_ROLE_BASIC_USER",
  GRANT_ROLE_GCS = "GRANT_ROLE_GCS",
  GRANT_ROLE_ADMIN = "GRANT_ROLE_ADMIN",
  GRANT_ROLE_QA_QC_USER = "GRANT_ROLE_QA_QC_USER",
  GRANT_TRADE_VISIBILITY = "GRANT_TRADE_VISIBILITY",

  READ = "READ",
  READ_BASIC_USERS = "READ_BASIC_USERS",
  READ_QA_QC_USERS = "READ_QA_QC_USERS",
  READ_GCS_USERS = "READ_GCS_USERS",
  READ_SUPERADMIN_USERS = "READ_SUPERADMIN_USERS",

  REVOKE_ROLE_SUPERADMIN = "REVOKE_ROLE_SUPERADMIN",
  REVOKE_ROLE_BASIC_USER = "REVOKE_ROLE_BASIC_USER",
  REVOKE_ROLE_GCS = "REVOKE_ROLE_GCS",
  REVOKE_ROLE_ADMIN = "REVOKE_ROLE_ADMIN",
  REVOKE_ROLE_QA_QC_USER = "REVOKE_ROLE_QA_QC_USER",
  REVOKE_TRADE_VISIBILITY = "REVOKE_TRADE_VISIBILITY",

  UPDATE = "UPDATE",
  UPDATE_ELEMENT_ADJACENCY = "UPDATE_ELEMENT_ADJACENCY",
  UPDATE_PROGRESS_REPORTS = "UPDATE_PROGRESS_REPORTS",
  UPDATE_QA_QC_COMPLETE = "UPDATE_QA_QC_COMPLETE",

  USE_REVIEW_MODE = "USE_REVIEW_MODE",
  USE_OPERATIONS_PAGE = "USE_OPERATIONS_PAGE",
  USE_INTEGRATIONS_PAGE = "USE_INTEGRATIONS_PAGE",
  USE_FILES_PAGE = "USE_FILES_PAGE",

  DELETE = "DELETE",
  DELETE_ELEMENT_ADJACENCY = "DELETE_ELEMENT_ADJACENCY"
}

export default UserPermissionAction;
